apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: redis
  replicas: 3  # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis/redis-stack:latest
          ports:
            - containerPort: 6379  # Default Redis port
          volumeMounts:
            - name: redis-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: redis-web-service
spec:
  selector:
    app: redis
  ports:
    - name: web
      protocol: TCP
      port: 8001  # The port you want to use for the web interface
      targetPort: 8001  # The port on which Redis web interface is running
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: redis-db-service
spec:
  selector:
    app: redis
  ports:
    - name: redis
      protocol: TCP
      port: 6379  # Port to access the Redis service within the cluster
      targetPort: 6379  # Port on which Redis is running
  type: ClusterIP