apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
spec:
  selector:
    app: streamlit-app
  ports:
    - protocol: TCP
      port: 8095  # The port on which the service will be accessible
      targetPort: 80  # The port your streamlit app is running on
  type: LoadBalancer  # Use LoadBalancer type if you're on a cloud provider that supports it
