authors:
  piyush:
    name: Piyush Anand
    description: TA
    avatar: https://github.com/piyush-an.png
  sri:
    name: Srikanth Krishnamurthy
    description: Professor
    avatar: https://media.licdn.com/dms/image/D4E03AQFDzqdrVZPH4g/profile-displayphoto-shrink_200_200/0/1678890711545?e=1703721600&v=beta&t=LpByhDHY4ATTwxjCWBdKq27MjbaxRtRm8ptnWgRUqj8