authors:
  piyush:
    name: Piyush Anand
    description: TA
    avatar: https://github.com/piyush-an.png
  sri:
    name: Srikanth Krishnamurthy
    description: Professor
    avatar: https://media.licdn.com/dms/image/D4E03AQHcxJHgNthnfA/profile-displayphoto-shrink_200_200/0/1706052826111?e=2147483647&v=beta&t=5_VYJ1r49IsBJq9Vu9UR0NqR8lYs8bqCYzu62MZbnC0